package com.revature.repositories;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.revature.models.Roles;
import com.revature.models.Users;

import util.ConnectionUtil;


public class UserPostgres implements UserDao{
	private static Logger log = LogManager.getRootLogger();
	
	/**
	 * Dao method to retrieve all employees
	 * @return a List of Employees or an empty list if none are found
	 */
	
	
	@Override
	public List<Users> getAllEmployee() {
		String sql = "select * from users u " + "join roles r on u.u_roleId = r.r_id;";
		
		List<Users> employees = new ArrayList<>();
		
		try (Connection connect = ConnectionUtil.getConnectionFromFile()) {
			Statement ps = connect.createStatement();
			ResultSet rs = ps.executeQuery(sql);
			
			while (rs.next()) {
				int id = rs.getInt("u_id");
				String firstName = rs.getString("u_first_name");
				String lastName = rs.getString("u_last_name");
				String username = rs.getString("u_username");
				String password = rs.getString("u_password");
				String email = rs.getString("u_email");
				int roleId = rs.getInt("u_roleId");
				String role = rs.getString("r_role"); 
				
				Roles role1 = new Roles(roleId,role);
				
				
				Users emp = new Users(id, username, password, firstName, lastName, email, role1);
				employees.add(emp);
				}
		
		} catch (SQLException |IOException e) {
			log.error("Error while trying to get item.");
			e.printStackTrace();
		} 
	return employees;
	}
	
	/**
	 * Dao method to retrieve employee by  id
	 * @param id of the employee
	 * @return an Employee or null if employee not found
	 */

	@Override
	public Users getEmployeeById(int id) {
		String sql = "select * from users where u_id = ? ";
		Users emp = null;
		
		try (Connection con = ConnectionUtil.getConnectionFromFile()) {
			PreparedStatement ps = con.prepareStatement(sql);

			ps.setInt(1, id);

			ResultSet rs = ps.executeQuery();

			if (rs.next()) {
				int id1 = rs.getInt("u_id");
				String firstName = rs.getString("u_first_name");
				String lastName = rs.getString("u_last_name");
				String username = rs.getString("u_username");
				String password = rs.getString("u_password");
				String email = rs.getString("u_email");
				int role = rs.getInt("u_roleid");
				
				emp = new Users(id1, username, password, firstName, lastName, email, role);
				
			}
		}catch (SQLException | IOException e) {
			e.printStackTrace();
		}
		return emp;
	}
	
	/**
	 * Dao method to create an employee, assigns an employee id generated by the database before returning
	 * @param employee object with all fields except for id
	 * @return an employee with an id or null if none is created
	 */

	@Override
	public Users addEmployee(Users employee) {
		// TODO Auto-generated method stub
		return null;
	}
	
	/**
	 * Dao method to update an employee
	 * @param employee object
	 * @return true if an employee was updated successfully, else false
	 */

	@Override
	public boolean updateEmployee(Users employee) {
		String sql = "update users set  u_username = ?,u_password = ?,u_first_name = ?,u_last_name = ?,u_email = ?"
						+ "Where u_id = ?;";
		int rowsChanged = -1;
		
		try (Connection con = ConnectionUtil.getConnectionFromFile()) {
			PreparedStatement ps = con.prepareStatement(sql);

			ps.setString(1, employee.getUsername());
			ps.setString(2, employee.getPassword());
			ps.setString(3, employee.getFirstName());
			ps.setString(4, employee.getLastName());
			ps.setString(5, employee.getEmail());
			ps.setInt(6, employee.getId());
			
			rowsChanged = ps.executeUpdate();
			
		}catch (SQLException | IOException e) {
				e.printStackTrace();
			}
		if (rowsChanged > 0) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public Users getEmployeeByUsername(String username) {
		String sql = "select * from users where u_username = ? ";
		Users emp = null;
		
		try (Connection con = ConnectionUtil.getConnectionFromFile()) {
			PreparedStatement ps = con.prepareStatement(sql);

			ps.setString(1, username);

			ResultSet rs = ps.executeQuery();

			if (rs.next()) {
				int id1 = rs.getInt("u_id");
				String firstName = rs.getString("u_first_name");
				String lastName = rs.getString("u_last_name");
				String username1 = rs.getString("u_username");
				String password = rs.getString("u_password");
				String email = rs.getString("u_email");
				int role = rs.getInt("u_roleid");
				
				emp = new Users(id1, firstName, lastName, username1, password, email, role);
				
			}
		}catch (SQLException | IOException e) {
			e.printStackTrace();
		}
		return emp;
	}

}
